// AUTO-GENERATED by scripts/generate-rule-registry.mjs — DO NOT EDIT.
// Run `pnpm gen` to regenerate; `pnpm gen:check` verifies it is up to date.
import type { GraphRule, Rule } from "./define-rule.js";
import { rule as awaitThenableRule } from "./rules/async/await-thenable.js";
import { rule as noAsyncPromiseExecutorRule } from "./rules/async/no-async-promise-executor.js";
import { rule as noAwaitInLoopRule } from "./rules/async/no-await-in-loop.js";
import { rule as noFloatingPromisesRule } from "./rules/async/no-floating-promises.js";
import { rule as noMisusedPromisesRule } from "./rules/async/no-misused-promises.js";
import { rule as noReturnAwaitRule } from "./rules/async/no-return-await.js";
import { rule as requireAwaitRule } from "./rules/async/require-await.js";
import { rule as explicitMemberAccessibilityRule } from "./rules/declaration-api/explicit-member-accessibility.js";
import { rule as explicitModuleBoundaryTypesRule } from "./rules/declaration-api/explicit-module-boundary-types.js";
import { rule as noExportAssignmentRule } from "./rules/declaration-api/no-export-assignment.js";
import { rule as noMutableExportsRule } from "./rules/declaration-api/no-mutable-exports.js";
import { rule as noEmptyCatchRule } from "./rules/error-handling/no-empty-catch.js";
import { rule as noErrorMessageMatchingRule } from "./rules/error-handling/no-error-message-matching.js";
import { rule as noExAssignRule } from "./rules/error-handling/no-ex-assign.js";
import { rule as noThrowInFinallyRule } from "./rules/error-handling/no-throw-in-finally.js";
import { rule as noUselessCatchRule } from "./rules/error-handling/no-useless-catch.js";
import { rule as onlyThrowErrorRule } from "./rules/error-handling/only-throw-error.js";
import { rule as preferErrorInstantiationRule } from "./rules/error-handling/prefer-error-instantiation.js";
import { rule as preferPromiseRejectErrorsRule } from "./rules/error-handling/prefer-promise-reject-errors.js";
import { rule as defaultCaseLastRule } from "./rules/exhaustiveness/default-case-last.js";
import { rule as noConstantConditionRule } from "./rules/exhaustiveness/no-constant-condition.js";
import { rule as noForInArrayRule } from "./rules/exhaustiveness/no-for-in-array.js";
import { rule as noUnnecessaryBooleanLiteralCompareRule } from "./rules/exhaustiveness/no-unnecessary-boolean-literal-compare.js";
import { rule as noUnnecessaryConditionRule } from "./rules/exhaustiveness/no-unnecessary-condition.js";
import { rule as preferDiscriminatedUnionRule } from "./rules/exhaustiveness/prefer-discriminated-union.js";
import { rule as preferNullishCoalescingRule } from "./rules/exhaustiveness/prefer-nullish-coalescing.js";
import { rule as switchExhaustivenessCheckRule } from "./rules/exhaustiveness/switch-exhaustiveness-check.js";
import { rule as genericNameConventionRule } from "./rules/generics/generic-name-convention.js";
import { rule as genericParamCountBudgetRule } from "./rules/generics/generic-param-count-budget.js";
import { rule as noGenericWithDefaultAnyRule } from "./rules/generics/no-generic-with-default-any.js";
import { rule as noUnnecessaryTypeConstraintRule } from "./rules/generics/no-unnecessary-type-constraint.js";
import { rule as preferGenericOverAnyPassthroughRule } from "./rules/generics/prefer-generic-over-any-passthrough.js";
import { rule as noDeepRelativeImportRule } from "./rules/module-boundaries/no-deep-relative-import.js";
import { rule as noDefaultExportRule } from "./rules/module-boundaries/no-default-export.js";
import { rule as publicApiMustBeExplicitRule } from "./rules/module-boundaries/public-api-must-be-explicit.js";
import { rule as consistentTypeDefinitionsRule } from "./rules/naming-idioms/consistent-type-definitions.js";
import { rule as noArrayConstructorRule } from "./rules/naming-idioms/no-array-constructor.js";
import { rule as noConstEnumRule } from "./rules/naming-idioms/no-const-enum.js";
import { rule as noEmptyInterfaceRule } from "./rules/naming-idioms/no-empty-interface.js";
import { rule as noInferrableTypeAnnotationRule } from "./rules/naming-idioms/no-inferrable-type-annotation.js";
import { rule as noJsonParseStringifyCloneRule } from "./rules/naming-idioms/no-json-parse-stringify-clone.js";
import { rule as noNamespaceRule } from "./rules/naming-idioms/no-namespace.js";
import { rule as noUnnecessaryTemplateLiteralRule } from "./rules/naming-idioms/no-unnecessary-template-literal.js";
import { rule as noVarRule } from "./rules/naming-idioms/no-var.js";
import { rule as pascalCaseTypesRule } from "./rules/naming-idioms/pascal-case-types.js";
import { rule as preferArrayMethodsRule } from "./rules/naming-idioms/prefer-array-methods.js";
import { rule as preferOptionalChainRule } from "./rules/naming-idioms/prefer-optional-chain.js";
import { rule as preferUnionOverEnumRule } from "./rules/naming-idioms/prefer-union-over-enum.js";
import { rule as tripleEqualsRule } from "./rules/naming-idioms/triple-equals.js";
import { rule as noEvalOrFunctionConstructorRule } from "./rules/security/no-eval-or-function-constructor.js";
import { rule as noImpliedEvalRule } from "./rules/security/no-implied-eval.js";
import { rule as noInsecureUrlRule } from "./rules/security/no-insecure-url.js";
import { rule as noNewBufferRule } from "./rules/security/no-new-buffer.js";
import { rule as noSecretsInSourceRule } from "./rules/security/no-secrets-in-source.js";
import { rule as enableExactOptionalPropertyTypesRule } from "./rules/strictness/enable-exact-optional-property-types.js";
import { rule as enableNoUncheckedIndexedAccessRule } from "./rules/strictness/enable-no-unchecked-indexed-access.js";
import { rule as enableStrictRule } from "./rules/strictness/enable-strict.js";
import { rule as enableUseUnknownInCatchRule } from "./rules/strictness/enable-use-unknown-in-catch.js";
import { rule as noAngleBracketAssertionRule } from "./rules/type-assertions/no-angle-bracket-assertion.js";
import { rule as noAssertionOnJsonParseRule } from "./rules/type-assertions/no-assertion-on-json-parse.js";
import { rule as noCastAfterGuardRule } from "./rules/type-assertions/no-cast-after-guard.js";
import { rule as noCastInReturnRule } from "./rules/type-assertions/no-cast-in-return.js";
import { rule as noDoubleAssertionRule } from "./rules/type-assertions/no-double-assertion.js";
import { rule as noNonNullAssertedOptionalChainRule } from "./rules/type-assertions/no-non-null-asserted-optional-chain.js";
import { rule as noNonNullAssertionRule } from "./rules/type-assertions/no-non-null-assertion.js";
import { rule as noTsIgnoreRule } from "./rules/type-assertions/no-ts-ignore.js";
import { rule as noTsNocheckRule } from "./rules/type-assertions/no-ts-nocheck.js";
import { rule as noUnnecessaryNonNullAssertionRule } from "./rules/type-assertions/no-unnecessary-non-null-assertion.js";
import { rule as noUnsafeObjectAssertionRule } from "./rules/type-assertions/no-unsafe-object-assertion.js";
import { rule as preferSatisfiesOverAsRule } from "./rules/type-assertions/prefer-satisfies-over-as.js";
import { rule as tsExpectErrorRequiresDescriptionRule } from "./rules/type-assertions/ts-expect-error-requires-description.js";
import { rule as noLargeIntersectionTypeRule } from "./rules/type-performance/no-large-intersection-type.js";
import { rule as noLargeUnionTypeRule } from "./rules/type-performance/no-large-union-type.js";
import { rule as preferInterfaceForLargeObjectTypeRule } from "./rules/type-performance/prefer-interface-for-large-object-type.js";
import { rule as anyDensityBudgetRule } from "./rules/type-safety/any-density-budget.js";
import { rule as noExplicitAnyRule } from "./rules/type-safety/no-explicit-any.js";
import { rule as noRecordStringUnknownRule } from "./rules/type-safety/no-record-string-unknown.js";
import { rule as noUnknownReturnRule } from "./rules/type-safety/no-unknown-return.js";
import { rule as noUnnecessaryInstanceofRule } from "./rules/type-safety/no-unnecessary-instanceof.js";
import { rule as noUnnecessaryTypeofRule } from "./rules/type-safety/no-unnecessary-typeof.js";
import { rule as noUnsafeArgumentRule } from "./rules/type-safety/no-unsafe-argument.js";
import { rule as noUnsafeCallRule } from "./rules/type-safety/no-unsafe-call.js";
import { rule as noUnsafeMemberAccessRule } from "./rules/type-safety/no-unsafe-member-access.js";
import { rule as noUnsafeReturnRule } from "./rules/type-safety/no-unsafe-return.js";
import { rule as noWrapperObjectTypesRule } from "./rules/type-safety/no-wrapper-object-types.js";
import { rule as preferTypeGuardPredicateRule } from "./rules/type-safety/prefer-type-guard-predicate.js";
import { rule as noUnusedExportsGraphRule } from "./rules/dead-code/no-unused-exports.js";
import { rule as noImportCyclesGraphRule } from "./rules/module-boundaries/no-import-cycles.js";

/** Every first-party per-file rule (SYN/TYP/CFG), in deterministic (category, id) order. */
export const ruleRegistry: Rule[] = [
  awaitThenableRule,
  noAsyncPromiseExecutorRule,
  noAwaitInLoopRule,
  noFloatingPromisesRule,
  noMisusedPromisesRule,
  noReturnAwaitRule,
  requireAwaitRule,
  explicitMemberAccessibilityRule,
  explicitModuleBoundaryTypesRule,
  noExportAssignmentRule,
  noMutableExportsRule,
  noEmptyCatchRule,
  noErrorMessageMatchingRule,
  noExAssignRule,
  noThrowInFinallyRule,
  noUselessCatchRule,
  onlyThrowErrorRule,
  preferErrorInstantiationRule,
  preferPromiseRejectErrorsRule,
  defaultCaseLastRule,
  noConstantConditionRule,
  noForInArrayRule,
  noUnnecessaryBooleanLiteralCompareRule,
  noUnnecessaryConditionRule,
  preferDiscriminatedUnionRule,
  preferNullishCoalescingRule,
  switchExhaustivenessCheckRule,
  genericNameConventionRule,
  genericParamCountBudgetRule,
  noGenericWithDefaultAnyRule,
  noUnnecessaryTypeConstraintRule,
  preferGenericOverAnyPassthroughRule,
  noDeepRelativeImportRule,
  noDefaultExportRule,
  publicApiMustBeExplicitRule,
  consistentTypeDefinitionsRule,
  noArrayConstructorRule,
  noConstEnumRule,
  noEmptyInterfaceRule,
  noInferrableTypeAnnotationRule,
  noJsonParseStringifyCloneRule,
  noNamespaceRule,
  noUnnecessaryTemplateLiteralRule,
  noVarRule,
  pascalCaseTypesRule,
  preferArrayMethodsRule,
  preferOptionalChainRule,
  preferUnionOverEnumRule,
  tripleEqualsRule,
  noEvalOrFunctionConstructorRule,
  noImpliedEvalRule,
  noInsecureUrlRule,
  noNewBufferRule,
  noSecretsInSourceRule,
  enableExactOptionalPropertyTypesRule,
  enableNoUncheckedIndexedAccessRule,
  enableStrictRule,
  enableUseUnknownInCatchRule,
  noAngleBracketAssertionRule,
  noAssertionOnJsonParseRule,
  noCastAfterGuardRule,
  noCastInReturnRule,
  noDoubleAssertionRule,
  noNonNullAssertedOptionalChainRule,
  noNonNullAssertionRule,
  noTsIgnoreRule,
  noTsNocheckRule,
  noUnnecessaryNonNullAssertionRule,
  noUnsafeObjectAssertionRule,
  preferSatisfiesOverAsRule,
  tsExpectErrorRequiresDescriptionRule,
  noLargeIntersectionTypeRule,
  noLargeUnionTypeRule,
  preferInterfaceForLargeObjectTypeRule,
  anyDensityBudgetRule,
  noExplicitAnyRule,
  noRecordStringUnknownRule,
  noUnknownReturnRule,
  noUnnecessaryInstanceofRule,
  noUnnecessaryTypeofRule,
  noUnsafeArgumentRule,
  noUnsafeCallRule,
  noUnsafeMemberAccessRule,
  noUnsafeReturnRule,
  noWrapperObjectTypesRule,
  preferTypeGuardPredicateRule,
];

/** Every first-party GRAPH-tier rule (module-graph analysis). */
export const graphRuleRegistry: GraphRule[] = [
  noUnusedExportsGraphRule,
  noImportCyclesGraphRule,
];
